language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: Um2Dv6QB2xikueh2J6UYKnGZ49qaHGzkw3RKkCiNmvd3m61zrK0SBp5TvV35JWanm+CCi1fR2q5D45Nx9mPECDCnMgxCaWK4aFEQowZt41/wL71rGvTQ98ifqQQqK7Hqfn4riF+dTpEGe/jLHQ9WFVPMPaIakFQhwYeO53yZt59iv608b2xJVXpBKXQ7hLv7IElwP8w6NOK6Qu1TDAmZ6hxcWMu4wxLqtOcneduA5mMPnHitHHlwtGpbIYIS+8Ba76g/kg3xIhd8fErqQf9IA7ZL/2gwmlERsTsOhA1SejIU4mG00DjLd7n2KbL2NWr0YvjN8EKBPG0pE/GLkWmRkQy3+SlZGqqYcMGffwXFXuI6PqPaNZAU0xwES4WkVF8xAPCh5vHjtgVGZZBgdgsGSd5rPDwj2gAj2cgXxLCa20zpheke1CGIsFzjWlMlj3mzCr0cvPE9HkNtxOvU7muWSex19fpUgv5rkyRn8urlUf1R0QMx8FDqjfruDGBknkL7F7RNMDehyV2XR0EBve2oomx/gv0Ojg8hyXuC/rOudl0V6ya0xUiIK22uijsKHJCumjSegSB/jSZdrhrA0OLQBFZm6/LEkUcK61QZwldcO8HyVm3IcD+2sIb9n5RLpxSIJtcEcppr1UWa1UL9AHWl1VRrju/t7lJudsMc+4RSheg=
  - secure: g3e1c2jo14rYr8k0IFjeU7IPgIXHxtBK3l3fSdAx2HN2/wUHHHnUpW7ykfvDkg3PRndbRFgq7JEd0UtocAdiN5HaN+KnYY8ZmNheWWqpBpWfvJqZ8i4sqYF8nrscsk2O9bbAa84/BwkVKkEOcMOHdZhHQt2WOLQ4bTVYhJD1DvJ+oWtXEOQbvx1RdxelxbyELqtMF1sCPGPZzkBByoBn0XaPstHECIPQqc5h79CZt3dLm/9ekoVs6Yo/LnvMRvuD17WWhAkbA1q3HhJFBQ0Bw971CODW5MtJ4z8ogGgfajG2zvrnovnPwnTDHSI6Gt1iow/LbDMUCLL2Yni/VIC5a9p0QgxjGxSXciC+VOlt9ocYMCMKoKVe1Xgkt9MDrFWvlafeC5cbIXXeGINsO8y6VvRKcwpbN3bmeiyxjriRM170it3iZ2FDw2MW6rpxsS/6JwY/FzVAb0sbuhB9r9wrC02I8w3WensK1BcTHOYDgy5rbqztPcu2bSxGePLQa6rWVXi/sJi9QjrorChPm0XKzCy9M98nvgmOCYFQd9BriBEBEGEJgkY+1cvykMN+ZXb7wub89wi3l6Bw9JAjOR96lmXuF2dUQ2/++qZEOf3R9ynBoZs+ehUcQmLy0TU2ZoTZw3Pya1G20vmfSzgVgK9LVN0FiBUnhfDyJfvS6M/ulyo=
